# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  daemon_terminattr:
    type: dict
    display_name: Daemon TerminAttr
    description: |
      Address of the gRPC server on CloudVision
      - TCP 9910 is used on on-prem
      - TCP 443 is used on CV as a Service
    keys:
      cvaddrs:
        type: list
        description: |
          Address for single cluster
        items:
          type: str
      clusters:
        type: list
        description: |
          For multiple cluster support
        primary_key: name
        convert_types:
        - dict
        items:
          type: dict
          keys:
            name:
              type: str
              required: true
              display_name: Cluster Name
            cvaddrs:
              type: list
              items:
                type: str
            cvauth:
              type: dict
              keys:
                method:
                  type: str
                  valid_values: ["token", "token-secure", "key"]
                key:
                  type: str
                token_file:
                  type: str
                  display_name: Path
                  description: |
                    Token file path
                    e.g. "/tmp/token"
            cvobscurekeyfile:
              type: bool
            cvproxy:
              type: str
              display_name: URL
            cvsourceip:
              type: str
              display_name: IP Address
            cvvrf:
              type: str
              display_name: VRF
      cvauth:
        type: dict
        description: |
          Authentication scheme used to connect to CloudVision
        keys:
          method:
            type: str
            valid_values: ["token", "token-secure", "key"]
          key:
            type: str
          token_file:
            type: str
            display_name: Path
            description: |
              Token file path
              e.g. "/tmp/token"
      cvobscurekeyfile:
        type: bool
        description: |
          The default compression scheme when streaming to CloudVision is gzip since TerminAttr 1.6.1 and CVP 2019.1.0. There is no need to change the compression scheme.
          Encrypt the private key used for authentication to CloudVision
      cvproxy:
        type: str
        display_name: URL
        description: |
          Proxy server through which CloudVision is reachable. Useful when the CloudVision server is hosted in the cloud.
          The expected form is http://[user:password@]ip:port, e.g.: 'http://arista:arista@10.83.12.78:3128'. Available as of TerminAttr v1.13.0
      cvsourceip:
        type: str
        display_name: IP Address
        description: |
          Set source IP address in case of in-band managament
      cvvrf:
        type: str
        display_name: VRF
        description: |
          Name of the VRF to use to connect to CloudVision
      cvgnmi:
        type: bool
        description: |
          Stream states from EOS GNMI servers (Openconfig) to CloudVision. Available as of TerminAttr v1.13.1
      disable_aaa:
        type: bool
        description: |
          Disable AAA authorization and accounting.
          When setting this flag, all commands pushed from CloudVision are applied directly to the CLI without authorization
      grpcaddr:
        type: str
        description: |
          Set the gRPC server address, the default is 127.0.0.1:6042
          e.g. "MGMT/0.0.0.0:6042"
      grpcreadonly:
        type: bool
        description: |
          gNMI read-only mode – Disable gnmi.Set()
      ingestexclude:
        type: str
        description: |
          Exclude paths from Sysdb on the ingest side.
          e.g. "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
      smashexcludes:
        type: str
        description: |
          Exclude paths from the shared memory table.
          e.g. "ale,flexCounter,hardware,kni,pulse,strata"
      taillogs:
        type: str
        description: |
          Enable log file collection; /var/log/messages is streamed by default if no path is set.
          e.g. "/var/log/messages"
      ecodhcpaddr:
        type: str
        description: |
          ECO DHCP Collector address or ECO DHCP Fingerprint listening addressin standalone mode (default "127.0.0.1:67")
      ipfix:
        type: bool
        description: |
          Enable IPFIX provider (default true).
          This flag is enabled by default and does not have to be added to the daemon configuration.
      ipfixaddr:
        type: str
        description: |
          ECO IPFIX Collector address to listen on to receive IPFIX packets (default "127.0.0.1:4739").
          This flag is enabled by default and does not have to be added to the daemon configuration
      sflow:
        type: bool
        description: |
          Enable sFlow provider (default true).
          This flag is enabled by default and does not have to be added to the daemon configuration
      sflowaddr:
        type: str
        description: |
          ECO sFlow Collector address to listen on to receive sFlow packets (default "127.0.0.1:6343").
          This flag is enabled by default and does not have to be added to the daemon configuration.

      cvcompression:
        type: str
      ingestauth_key:
        type: str
      ingestgrpcurl:
        type: dict
        keys:
          ips:
            type: list
            items:
              type: str
          port:
            type: int
            convert_types:
            - str
      ingestvrf:
        type: str
