# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  ip_access_lists:
    type: list
    primary_key: name
    convert_types:
    - dict
    items:
      type: dict
      keys:
        name:
          type: str
          required: true
          display_name: Access-list Name
        counters_per_entry:
          type: bool
        entries:
          type: list
          display_name: Remark Entry
          items:
            type: dict
            keys:
              sequence:
                type: int
                convert_types:
                - str
                description: |
                  ACL entry sequence number
              remark:
                type: str
                description: |
                  Comment up to 100 characters
              action:
                type: str
                valid_values: ["permit", "deny"]
              protocol:
                type: str
                description: |
                  ip | tcp | udp | icmp | other protocol name or number.
              source:
                type: str
                description: |
                  NOTE: A.B.C.D without a mask means host
              source_ports_match:
                type: str
                valid_values: ["eq", "gt", "lt", "neq", "range"]
                default: "eq"
              source_ports:
                type: list
                items:
                  type: int
                  convert_types:
                  - str
                  description: |
                    tcp/udp port name or number
              destination:
                type: str
                description: |
                  NOTE: A.B.C.D without a mask means host
              destination_ports_match:
                type: str
                valid_values: ["eq", "gt", "lt", "neq", "range"]
                default: "eq"
              destination_ports:
                type: list
                items:
                  type: int
                  convert_types:
                  - str
                  description: |
                    TCP/UDP port name or number
              tcp_flags:
                type: list
                items:
                  type: str
                  display_name: TCP Flag Name
              fragments:
                type: bool
                description: |
                  Match non-head fragment packets
              log:
                type: bool
                description: |
                  Log matches against this rule
              ttl:
                type: int
                display_name: TTL value
                convert_types:
                - str
              ttl_match:
                type: str
                valid_values: ["eq", "gt", "lt", "neq"]
                default: "eq"
              icmp_type:
                type: str
                convert_types:
                - int
                description: |
                  Message type name/number for ICMP packets.
              icmp_code:
                type: str
                convert_types:
                - int
                description: |
                  Message code for ICMP packets
              nexthop_group:
                type: str
                display_name: Nexthop-Group Name
              tracked:
                type: bool
                description: |
                  Match packets in existing ICMP/UDP/TCP connections.
              dscp:
                type: str
                convert_types:
                - int
                display_name: DSCP Name
              vlan_number:
                type: int
                convert_types:
                - str
              vlan_inner:
                type: bool
                default: false
              vlan_mask:
                type: str
                description: |
                  0x000-0xFFF  Vlan mask
