# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
allow_other_keys: true
keys:
  maintenance:
    type: dict
    display_name: Profiles and units
    keys:
      default_interface_profile:
        type: str
        description: |
          Name of default Interface Profile
      default_bgp_profile:
        type: str
        description: |
          Name of default BGP Profile
      default_unit_profile:
        type: str
        description: |
          Name of default Unit Profile
      interface_profiles:
        type: list
        primary_key: name
        convert_types:
        - dict
        items:
          type: dict
          keys:
            name:
              type: str
              required: true
            rate_monitoring:
              type: dict
              keys:
                load_interval:
                  type: int
                  description: |
                    Load Interval in Seconds
                threshold:
                  type: int
            shutdown:
              type: dict
              keys:
                max_delay:
                  type: int
      bgp_profiles:
        type: list
        primary_key: name
        convert_types:
        - dict
        items:
          type: dict
          keys:
            name:
              type: str
              required: true
              display_name: BGP Profile Name
            initiator:
              type: dict
              keys:
                route_map_inout:
                  type: int
                  display_name: Route Map
      unit_profiles:
        type: list
        primary_key: name
        convert_types:
        - dict
        items:
          type: dict
          keys:
            name:
              type: str
              required: true
              display_name: Unit Profile Name
            on_boot:
              type: dict
              keys:
                duration:
                  type: int
      units:
        type: list
        primary_key: name
        convert_types:
        - dict
        items:
          type: dict
          keys:
            name:
              type: str
              required: true
              display_name: Unit Name
            quiesce:
              type: bool
            profile:
              type: str
              required: true
              description: |
                Name of Unit Profile
            groups:
              type: dict
              keys:
                bgp_groups:
                  type: list
                  items:
                    type: str
                    description: |
                      Name of BGP Group
                interface_groups:
                  type: list
                  items:
                    type: str
                    description: |
                      Name of Interface Group
