---
- name: topology
  hosts: localhost
  connection: local
  tasks:
    - name: Generate topology diagram from structure config in svg format
      tags: [always]
      arista.avd.topology_generator:
        structured_config: "./structured_configs_v1"
      delegate_to: localhost
