### Sflow ###
sflow:
  vrfs:
    - name: MGMT
      destinations:
        - sflow_destination_ip: 10.6.75.62
          port: 123
        - sflow_destination_ip: 10.6.75.63
          port: 333
        - sflow_destination_ip: 10.6.75.59
      source_interface: Ethernet3
    - name: AAA
      destinations:
        - sflow_destination_ip: 10.6.75.62
          port: 123
        - sflow_destination_ip: 10.6.75.63
          port: 333
      source_interface: Ethernet2
  destinations:
    - sflow_destination_ip: 10.6.75.62
      port: 123
    - sflow_destination_ip: 10.6.75.61
  source_interface: Management0
  sample: 1000
  dangerous: true
  run: true
